import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'ar';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, any>> = {
  fr: {
    // Preloader
    'preloader.title': 'CARPÔLE INDUSTRIEL',
    'preloader.location': 'Constantine, Algérie',
    // Navbar
    'navbar.accueil': 'Accueil',
    'navbar.services': 'Nos services',
    'navbar.simulateur': 'Demander un devis',
    'navbar.galerie': 'Galerie Réalisations',
    'navbar.propos': 'À propos',
    'navbar.contact': 'Contact',
    'navbar.cta': 'Demander un devis',
    // Hero
    'hero.location': 'Constantine, Algérie',
    'hero.badgeText': 'Expertise carrosserie & frigorifique',
    'hero.title1': 'L’EXCELLENCE INDUSTRIELLE',
    'hero.title2': 'Pour votre Flotte Frigorifique',
    'hero.desc': 'Carpôle Industriel conçoit, fabrique et installe des carrosseries isothermes et des groupes frigorifiques hautes performances à Constantine. Sécurisez la chaîne du froid de vos transports routiers en Algérie.',
    'hero.cta_simulateur': 'Demander un devis',
    'hero.cta_services': 'Découvrir nos services',
    'hero.explorer': 'Explorer',
    // Stats
    'stats.0.value': '15+',
    'stats.0.label': 'Années d’Expérience',
    'stats.0.desc': 'Savoir-faire artisanal',
    'stats.1.value': '200+',
    'stats.1.label': 'Camions Transformés',
    'stats.1.desc': 'À travers l’Algérie entière',
    'stats.2.value': '100%',
    'stats.2.label': 'Normes ATP Respectées',
    'stats.2.desc': 'Garantie de chaîne de froid',
    'stats.3.value': '24/7',
    'stats.3.label': 'Support Technique',
    'stats.3.desc': 'Assistance & maintenance à Constantine',
    // ServicesSection
    'services.badge': 'Savoir-Faire Certifié',
    'services.title': 'Nos Métiers de l’Isolation & du Froid',
    'services.subtitle': 'De la tôle robuste aux groupes réfrigérants intelligents, nous offrons une synergie d’ingénierie mécanique et thermique pour équiper vos véhicules utilitaires.',
    'services.learn_more': 'En savoir plus',
    'services.view_main': 'VUE PRINCIPALE',
    'services.view_tech': 'VUE TECHNIQUE',
    'services.carrosserie.principale.title': 'Isolation renforcée sous vide pour le transport basse température (-20°C) de produits congelés.',
    'services.carrosserie.principale.desc': 'Nos ingénieurs et techniciens réalisent ces assemblages certifiés au sein de notre atelier moderne à Constantine, validant chaque étape selon de sévères critères d\'isolation thermique.',
    'services.carrosserie.engineering_title': 'ATOUTS D\'INGÉNIERIE INTÉGRÉS',
    'services.carrosserie.security_title': 'SÉCURITÉ THERMIQUE CERTIFIÉE',
    'services.char.thickness': 'ÉPAISSEUR ISOLATION',
    'services.char.thickness_val': '80 mm à 100 mm',
    'services.char.k_coeff': 'COEFF. TRANSMISSION K',
    'services.char.k_coeff_val': '0,36 W/m²K (Certifié)',
    'services.char.temp': 'TEMPÉRATURE DE SERVICE',
    'services.char.temp_val': '-20°C à -25°C',
    'services.char.atp': 'HOMOLOGATION ATP',
    'services.char.atp_val': 'FRC (Classe C)',
    'services.specifications_title': 'Spécifications Techniques & Atouts',
    'services.duration_label': 'Durée de réalisation :',
    'services.duration_label_avg': 'Durée moyenne de réalisation :',
    'services.duration.carrosserie': '6-14 jours',
    'services.duration.refrigeration': '3-5 jours',
    'services.duration.maintenance': '1-2 jours',
    'services.estimate_btn': 'Estimer un prix pour ce travail',
    'services.engineering_sheet': 'FICHE D\'INGÉNIERIE CARPÔLE',
    'services.sheet_title': 'CARROSSERIE ISOTHERME RENFORCÉE (CLASSE C)',
    'services.sheet_subtitle': 'PANNEAUX SANDWICH HAUTE PERFORMANCE 100MM',
    'services.warranty_title': 'Garantie & Homologation',
    'services.warranty_desc': 'Certificat de conformité agréé par l’État algérien.',
    'services.key_assets': 'Atouts clés',
    'services.characteristics': 'Caractéristiques',
    // Services Data
    'services.carrosserie.title': 'Installation de Carrosserie Camion',
    'services.carrosserie.description': 'Conception et montage de carrosseries industrielles robustes : fourgons isolants, plateaux ridelles et bennes renforcées.',
    'services.carrosserie.longDescription': 'Nous fabriquons et assemblons des carrosseries industrielles sur-mesure adaptées à tous types de châssis de camions (petites camionnettes, porteurs moyens et poids lourds). En utilisant des panneaux isolants haute intensité et des profilés métalliques inoxydables de qualité supérieure, nous garantissons l’étanchéité, la durabilité et la résistance mécanique face aux conditions climatiques et routières d’Algérie.',
    'services.carrosserie.adv.0': 'Panneaux composites renforcés de haute densité',
    'services.carrosserie.adv.1': 'Plancher antidérapant étanche et ultra-résistant',
    'services.carrosserie.adv.2': 'Profilés d’angle en aluminium anodisé ou inox',
    'services.carrosserie.adv.3': 'Homologation conforme aux normes de sécurité et de charge',
    'services.carrosserie.adv.4': 'Garantie constructeur de 24 mois sur la structure',

    'services.refrigeration.title': 'Installation de Groupes Frigorifiques',
    'services.refrigeration.description': 'Intégration de frigos performants pour transport de denrées périssables, produits laitiers et pharmaceutiques (frais et congelé).',
    'services.refrigeration.longDescription': 'Nous sommes spécialisés dans l’intégration et la maintenance de solutions de réfrigération de transport (groupes frigorifiques de grandes marques) montées sur la face avant ou en sous-châssis. Du maintien de température fraîcheur (+2°C à +4°C) au gel surgelé extrême (-20°C), nos installations respectent scrupuleusement la chaîne du froid pour la livraison logistique agroalimentaire et pharmaceutique.',
    'services.refrigeration.adv.0': 'Régulation de température ultra-précise par microprocesseur',
    'services.refrigeration.adv.1': 'Moteurs thermiques ou électriques bi-énergie (Route/Secteur)',
    'services.refrigeration.adv.2': 'Isolation thermique à très faible coefficient de conductivité',
    'services.refrigeration.adv.3': 'Attestation de conformité technique de salubrité frigorifique',
    'services.refrigeration.adv.4': 'Service de maintenance préventive et d’urgence 24h/7j',

    'services.maintenance.title': 'Maintenance & Service Après-Vente',
    'services.maintenance.description': 'Réparation rapide des ponts thermiques, réparation de carrosserie endommagée et recharge en gaz frigorifique.',
    'services.maintenance.longDescription': 'Un camion immobilisé est une perte pour votre entreprise. Nous mettons à disposition un atelier complet à Constantine pour effectuer les recharges de gaz de refroidissement (R404A, R452A), la détection des fuites, le redressage de carrosserie, le remplacement des joints d’étanchéité de portes et la réparation des panneaux sandwich composites.',
    'services.maintenance.adv.0': 'Diagnostic technique complet informatisé',
    'services.maintenance.adv.1': 'Recharge écologique certifiée et réparation de compresseurs',
    'services.maintenance.adv.2': 'Remplacement rapide des charnières et joints de portes usés',
    'services.maintenance.adv.3': 'Soudure inox/aluminium professionnelle',
    'services.maintenance.adv.4': 'Pièces de rechange d’origine garanties',

    // Quote Simulator Extra
    'quote.title': 'Simulateur de Tarification Industrielle',
    'quote.subtitle': 'Configurez votre projet en quelques clics et obtenez une estimation budgétaire transparente en Dinars Algériens (DZD).',
    'quote.step1': '1. Configuration du Camion',
    'quote.step2': '2. Coordonnées de Contact',
    'quote.truck_type': 'Catégorie et taille du camion',
    'quote.truck.carrier_small': 'Petit utilitaire et véhicule utilitaire (<3.5t)',
    'quote.truck.carrier_small.desc': 'Ex: Hyundai Porter, Kia K2500, DFAC...',
    'quote.truck.truck_medium': 'Camion moyen tonnage (3.5t à 12t)',
    'quote.truck.truck_medium.desc': 'Ex: Isuzu NPR, JMC, Renault Gamme D...',
    'quote.truck.semi_heavy_duty': 'Poids lourd rigide (12t à 19t)',
    'quote.truck.semi_heavy_duty.desc': 'Ex: Mercedes Actros rigide, Volvo FE...',
    'quote.truck.special_order': 'Commande spéciale / Projet sur-mesure',
    'quote.truck.special_order.desc': 'Ex: Dépanneuse, plateau de remorquage, grue d’atelier, nacelle...',
    'quote.body_type': 'Type de carrosserie souhaité',
    'quote.body.insulated_refrigerated': 'Isotherme Renforcée (Frigo)',
    'quote.body.insulated_refrigerated.desc': 'Panneaux sandwichs étanches haute densité',
    'quote.body.standard_box_dry': 'Fourgon tôlé standard (Caisse sèche)',
    'quote.body.standard_box_dry.desc': 'Parois robustes en aluminium pour marchandises générales et colis',
    'quote.body.meat_hanging': 'Isotherme Viandes Suspendues (Penderie)',
    'quote.body.meat_hanging.desc': 'Rails renforcés fixés au plafond avec crochets en inox',
    'quote.body.subframe_only': 'Faux-châssis nu uniquement',
    'quote.body.subframe_only.desc': 'Structure métallique d’adaptation prête pour votre équipement',
    'quote.frigo_capacity': 'Capacité frigorifique requise',
    'quote.frigo.none': 'Aucune (Transport sec / simple isotherme sans moteur)',
    'quote.frigo.none.desc': 'Sans unité de production de froid active',
    'quote.frigo.positive_fresh': 'Froid positif fraîcheur (+2°C à +4°C)',
    'quote.frigo.positive_fresh.desc': 'Idéal pour produits laitiers, fruits, légumes, fleurs...',
    'quote.frigo.negative_deep_freeze': 'Froid négatif surgelés (-18°C à -20°C)',
    'quote.frigo.negative_deep_freeze.desc': 'Pour crèmes glacées, viandes, poissons et produits congelés',
    'quote.frigo.dual_multi_temp': 'Multi-température (Double compartiment)',
    'quote.frigo.dual_multi_temp.desc': 'Cloison de séparation pour frais et congelé simultanément',
    'quote.options': 'Options additionnelles',
    'quote.option.subframe': 'Faux-châssis galvanisé traité anticorrosion',
    'quote.truck_count': 'Nombre de véhicules à équiper',
    'quote.client.title': 'Vos coordonnées pour finaliser le devis',
    'quote.client.desc': 'Un conseiller technique de Constantine vous contactera sous 24 heures pour valider votre projet.',
    'quote.client.name': 'Nom complet / Contact principal',
    'quote.client.phone': 'N° de téléphone (Algérie)',
    'quote.client.email': 'Adresse email professionnelle',
    'quote.client.company': 'Nom de l’entreprise (Optionnel)',
    'quote.client.city': 'Ville d’exploitation principale',
    'quote.client.notes': 'Instructions spécifiques ou demandes particulières',
    'quote.btn.previous': 'Étape précédente',
    'quote.btn.next': 'Continuer',
    'quote.btn.reset': 'Réinitialiser le simulateur',
    'quote.result.title': 'Votre estimation budgétaire',
    'quote.result.subtitle': 'Estimation du coût basé sur nos tarifs d’atelier à Constantine',
    'quote.result.bodywork': 'Coût de la carrosserie',
    'quote.result.frigo': 'Coût du groupe frigorifique',
    'quote.result.subframe': 'Coût du faux-châssis',
    'quote.result.engineering': 'Ingénierie, pose et raccordement cabine',
    'quote.result.ht': 'Sous-total Hors Taxes (HT)',
    'quote.result.tva': 'TVA estimée (19%)',
    'quote.result.ttc': 'Total Toutes Taxes Comprises (TTC)',
    'quote.result.duration': 'Délai d’atelier estimé',
    'quote.result.warranty': 'Garantie constructeur standard',
    'quote.result.note': 'Ce devis est une estimation. L’offre définitive sera établie après examen technique.',
    'quote.result.pdf': 'Télécharger le devis au format PDF',
    'quote.result.contact': 'Prendre rendez-vous à l’atelier de Constantine',
    'quote.pdf.alert': 'Génération du PDF en cours...',
    'quote.rdv.alert': 'Demande de rendez-vous enregistrée.',

    'quote.free_estimate_badge': 'Demande de devis gratuit',
    'quote.step1_title': '1. TYPE DE CHÂSSIS / VÉHICULE',
    'quote.step2_title': '2. TYPE DE STRUCTURE / CARROSSERIE',
    'quote.step3_title': '3. CAPACITÉ DE RÉFRIGÉRATION / FROID',
    'quote.step4_title': '4. NOMBRE DE CAMIONS À ÉQUIPER',
    'quote.subframe_option': 'Faux-châssis galva',
    'quote.subframe_desc': 'Traitement anticorrosion',
    'quote.notes_placeholder': 'Ex: Demande de hayon élévateur, séparation par cloison amovible mobile, double porte latérale, rayonnage d\'étagères repliables...',
    'quote.result.title_badge': 'FICHE TECHNIQUE DE DEVIS',
    'quote.result.recap_title': 'Récapitulatif de Configuration',
    'quote.result.carrier': '1. Véhicule & Châssis',
    'quote.result.structure': '2. Type de Structure',
    'quote.result.cooling': '3. Volume Froid / Réfrigération',
    'quote.result.quantity': '4. Quantité de Véhicules',
    'quote.result.additional': 'Options Additionnelles',
    'quote.result.subframe_galva': 'Faux-châssis galvanisé traité anti-corrosion',
    'quote.result.delay_label': 'Délai d’Atelier Estimatif :',
    'quote.result.warranty_label': 'Garantie Carpôle :',
    'services.mois': 'mois',
    'quote.result.delivery_place': 'Lieu de livraison :',
    'quote.result.delivery_val': 'Atelier Constantine',
    'quote.client.name_placeholder': 'Ex: Karim Benhadj',
    'quote.client.phone_placeholder': 'Ex: 0550 XX XX XX',
    'quote.client.company_placeholder': 'Ex: SARL Trans Logistics Froid',
    'quote.result.notice': 'Pour vous garantir la meilleure qualité au meilleur prix d’Algérie, chaque devis est calculé sur-mesure par nos ingénieurs d’assemblage selon vos besoins réels.',
    'quote.success.title': 'Demande de Devis Envoyée !',
    'quote.success.thank_you': 'Merci {name}. Votre demande de configuration a été enregistrée avec succès sous la référence unique {ref}.',
    'quote.success.recap': 'RÉCAPITULATIF REÇU',
    'quote.success.flotte': 'Flotte configurée :',
    'quote.success.structure': 'Structure / Carrosserie :',
    'quote.success.cooling_sys': 'Système Froid :',
    'quote.success.subframe': 'Sous-chassis :',
    'quote.success.subframe_val': 'Faux-châssis galva inclus',
    'quote.success.notice': 'Un ingénieur de notre bureau d’études de Constantine prépare l’étude de prix de votre projet et vous contactera au {phone} sous 60 minutes pour affiner les schémas techniques de construction de vos camions.',
    'quote.success.btn_another': 'Faire une autre demande de devis',
    'quote.error_fill': 'Veuillez remplir votre nom et votre numéro de téléphone.',
    'quote.body_warning': '* L’installation d’un groupe frigorifique nécessite une structure & carrosserie de type "Isotherme Renforcée (Frigo)".',
    'quote.days_work': 'Jours ouvrés',

    // GallerySection
    'gallery.title': 'Galerie de Réalisations',
    'gallery.subtitle': 'Découvrez nos derniers chantiers livrés depuis nos ateliers de Constantine.',
    'gallery.cat.all': 'Toutes les réalisations',
    'gallery.cat.carrosserie': 'Carrosseries Isothermes',
    'gallery.cat.frigo': 'Groupes Frigorifiques',
    'gallery.cat.realisation': 'Véhicules Prêts à Livrer',
    'gallery.location_prefix': 'Lieu : ',
    'gallery.real_label': 'Galerie Photos Réelles',
    'gallery.imm_title': 'Immersion dans Nos Ateliers de Constantine',
    'gallery.imm_desc': 'Consultez les photos professionnelles de nos compagnons installant des parois sandwiches de précision et connectant les circuits d’énergie frigorifiques.',
    'gallery.cat_body': 'Soudure & Carrosserie',
    'gallery.cat_cooling': 'Montage Frigorifique',
    'gallery.cat_deliv': 'Livraison Client',
    'gallery.std_title': 'Standard de réalisation',
    'gallery.std_item1': 'Inspections thermiques infrarouge',
    'gallery.std_item2': 'Mise sous pression et test de gaz étanche',
    'gallery.std_item3': 'Fermetures inox anti-vibration',
    'gallery.std_btn': 'Estimer un équipement similaire',
    'gallery.item.real-1.title': 'Montage de carrosserie isotherme',
    'gallery.item.real-1.desc': 'Techniciens en plein assemblage de panneaux composites isolés haute densité sur un porteur rigide dans notre nouvel atelier.',
    'gallery.item.real-1.loc': 'Atelier Central, Constantine',
    'gallery.item.real-2.title': 'Installation d’un groupe frigorifique Carrier',
    'gallery.item.real-2.desc': 'Pose finale et raccordement électrique d’un système de froid négatif (-18°C) sur la cloison frontale d’un camion de distribution de produits surgelés.',
    'gallery.item.real-2.loc': 'Zone Industrielle, Constantine',
    'gallery.item.real-3.title': 'Camion frigorifique prêt à la livraison',
    'gallery.item.real-3.desc': 'Projet d’intégration complet (carrosserie isolée étanche + groupe de réfrigération thermo-contrôlé) livré pour une entreprise de logistique laitière nationale.',
    'gallery.item.real-3.loc': 'Hauts Plateaux, Constantine',
    'gallery.item.real-4.title': 'Aménagement intérieur isotherme de précision',
    'gallery.item.real-4.desc': 'Plancher en aluminium strié étanche, rails d’arrimage et rideaux thermiques à lanières pour minimiser les pertes de frigories au déchargement.',
    'gallery.item.real-4.loc': 'Atelier de Finition, Constantine',
    'gallery.item.real-5.title': 'Flotte de camions de distribution',
    'gallery.item.real-5.desc': 'Livraison simultanée de trois gros porteurs frigorifiques équipés de cloisons amovibles multi-températures pour la distribution urbaine.',
    'gallery.item.real-5.loc': 'Constantine, Algérie',
    'gallery.item.real-6.title': 'Camion frigorifique prêt à la livraison',
    'gallery.item.real-6.desc': 'Projet d’intégration complet (carrosserie isolée étanche + groupe de réfrigération thermo-contrôlé) livré pour une entreprise de logistique laitière nationale.',
    'gallery.item.real-6.loc': 'Hauts Plateaux, Constantine',

    // AboutSection
    'about.badge': 'Qui sommes-nous ?',
    'about.title1': 'Carpôle Industriel :',
    'about.title2': 'La Référence du Froid Routier',
    'about.p1': 'Basée à Constantine, cœur logistique de l’Est algérien, l’entreprise Carpôle Industriel est née de la volonté de fournir aux transporteurs et entreprises alimentaires des équipements isothermes et frigorifiques d’une fiabilité absolue.',
    'about.p2': "Nous associons des techniques modernes d'isolation composite (panneaux sandwich étanches ultra-légers) avec des compétences de chaudronnerie lourde pour garantir des installations robustes. Qu'il s’agisse d'un petit utilitaire pour les livraisons en centre-ville ou d’un ensemble lourd articulé, nous adaptons les puissances frigorifiques pour supporter les chaleurs extrêmes du climat algérien.",
    'about.val.0.title': 'Zéro Pont Thermique',
    'about.val.0.desc': 'Notre procédé de thermo-moulage de cloisons isole hermétiquement la cargaison.',
    'about.val.1.title': 'Savoir-Faire Soudeur',
    'about.val.1.desc': 'Soudure et fixation de faux-châssis exécutées en acier trempé traité antirouille.',
    'about.val.2.title': 'Homologation d’État',
    'about.val.2.desc': 'Toutes nos transformations obtiennent le certificat officiel de réception par les Mines.',
    'about.val.3.title': 'Accompagnement Local',
    'about.val.3.desc': 'Atelier de proximité basé à Constantine pour un entretien rapide de votre flotte.',
    'about.sede': 'Siège Social & Atelier Central',
    'about.address': 'Chaab ersas lot F numero M1, Constantine, Algérie',
    'about.extra_title': 'Vous possédez déjà votre groupe frigorifique ?',
    'about.extra_desc': 'Nous assurons l’installation mécanique et le montage électrique de vos propres boîtiers de réfrigération (neufs ou occasions révisés) à des tarifs compétitifs, avec raccordement cabine sécurisé.',
    'about.extra_btn': 'Parler à un installateur',

    // Testimonials
    'testimonials.title': 'Ce que disent nos clients',
    'testimonials.role1': 'Directeur Logistique',
    'testimonials.company1': 'Laiterie du Constantinois',
    'testimonials.comment1': 'Nous avons confié l’équipement de nos 12 camions de collecte et de distribution à Carpôle Industriel. La qualité de l’isolation isotherme est impeccable, même sous la canicule de l’Est algérien. Les températures de consigne restent stables et la consommation de carburant de nos groupes frigorifiques est optimisée.',
    'testimonials.role2': 'Artisan Transporteur',
    'testimonials.company2': 'Zouaoui & Fils Trans-Froid',
    'testimonials.comment2': 'Excellent service après-vente ! Suite à un accrochage sur la route de Batna, ils ont réparé le flanc de ma carrosserie isotherme et changé le condenseur du frigo en moins de 48 heures. Rapidité et professionnalisme inégalés à Constantine.',
    'testimonials.role3': 'Gérante Approvisionnements',
    'testimonials.company3': 'PharmEst Algérie',
    'testimonials.comment3': 'Pour la distribution de produits pharmaceutiques sensibles, la certification et l’étalonnage précis de la température sont rigoureux. Le simulateur de devis de Carpôle nous a permis de planifier nos budgets d’investissement avec précision et leur équipe technique a parfaitement intégré le double compartiment multi-température.',

    // ContactSection
    'contact.title': 'Une question ? Un projet ?',
    'contact.subtitle': 'Notre équipe commerciale et nos ingénieurs sont à votre écoute pour concevoir vos véhicules.',
    'contact.info.title': 'Nos Coordonnées',
    'contact.info.tel': 'Téléphone & WhatsApp',
    'contact.info.email': 'Email de contact',
    'contact.info.addr': 'Adresse de l’Atelier',
    'contact.info.addr_desc': 'Chaab ersas lot F numero M1, Constantine',
    'contact.info.hours': 'Heures d’ouverture',
    'contact.info.hours_desc': 'Samedi - Jeudi : 08:00 - 17:00 (Fermé le Vendredi)',
    'contact.form.name': 'Nom complet',
    'contact.form.company': "Nom de l'entreprise",
    'contact.form.email': 'Adresse email',
    'contact.form.subject': 'Sujet du message',
    'contact.form.message': 'Votre message',
    'contact.form.send': 'Envoyer le message',
    'contact.form.placeholder.name': 'Ex: Ahmed Benali',
    'contact.form.placeholder.company': 'Ex: SARL TransLogistics',
    'contact.form.placeholder.email': 'Ex: contact@entreprise.dz',
    'contact.form.placeholder.subject': 'Ex: Demande de tarif carrosserie isotherme pour ISUZU',
    'contact.form.placeholder.message': 'Décrivez votre projet de carrosserie, le modèle de châssis et la température requise...',
    'contact.form.success': 'Votre message a été envoyé avec succès ! Notre équipe commerciale vous répondra rapidement.',
    'contact.faq.title': 'Questions Fréquentes',
    'contact.faq.0.q': 'Qu’est-ce que la certification thermique ATP et d’Algérie ?',
    'contact.faq.0.a': 'La certification de conformité isotherme est un document réglementaire obligatoire délivré après montage par notre service agréé. Elle atteste que notre paroi et le groupe frigorifique maintiennent la température (-20°C ou +4°C) requise pour la santé publique face aux températures caniculaires algériennes.',
    'contact.faq.1.q': 'Quelles marques de frigos installez-vous sur les camions ?',
    'contact.faq.1.a': 'Nous installons et raccordons des groupes frigorifiques de classe mondiale tels que Carrier, Thermo King, Zanotti et Dongin Thermo. Notre atelier possède toutes les buses, faisceaux d’origine et calculateurs numériques de reprogrammation pour ces marques.',
    'contact.faq.2.q': 'Proposez-vous le service d’entretien de la carrosserie seulement ?',
    'contact.faq.2.a': 'Oui absolument. En dehors de l’assemblage initial, notre atelier effectue la re-conception, la réparation des ponts thermiques de cloisons endommagées, la soudure inox du plancher, le changement de rideaux à lanières et la correction des étanchéités de portes arrières.',
    'contact.faq.3.q': 'Quels sont vos délais d’intervention à Constantine ?',
    'contact.faq.3.a': 'Pour une simple pose de groupe frigorifique, le délai est de 2 à 4 jours ouvrés. Pour une structure de carrosserie isotherme complète fabriquée sur-mesure (panneaux + faux-châssis + frigo), comptez entre 6 et 14 jours selon le volume du châssis carrossé.',

    // Footer
    'footer.desc': "Le leader de la carrosserie et du froid industriel dans l'Est Algérien.",
    'footer.links': 'Liens Rapides',
    'footer.rights': 'Tous droits réservés.',
  },
  ar: {
    // Preloader
    'preloader.title': 'كاربول الصناعية',
    'preloader.location': 'قسنطينة، الجزائر',
    // Navbar
    'navbar.accueil': 'الرئيسية',
    'navbar.services': 'خدماتنا',
    'navbar.simulateur': 'طلب تقدير سعر',
    'navbar.galerie': 'معرض الإنجازات',
    'navbar.propos': 'من نحن',
    'navbar.contact': 'اتصل بنا',
    'navbar.cta': 'طلب تقدير سعر',
    // Hero
    'hero.location': 'قسنطينة، الجزائر',
    'hero.badgeText': 'خبرة في الهياكل والتبريد الشاحنات',
    'hero.title1': 'التميز الصناعي',
    'hero.title2': 'لأسطول شاحنات التبريد الخاص بك',
    'hero.desc': 'يقوم كاربول الصناعي بتصميم وتصنيع وتركيب الهياكل العازلة ووحدات التبريد عالية الأداء في قسنطينة. قم بتأمين سلسلة التبريد لعمليات النقل البري في الجزائر.',
    'hero.cta_simulateur': 'طلب تقدير سعر',
    'hero.cta_services': 'اكتشف خدماتنا',
    'hero.explorer': 'استكشف',
    // Stats
    'stats.0.value': '15+',
    'stats.0.label': 'سنة من الخبرة',
    'stats.0.desc': 'حرفية وخبرة فنية عالية',
    'stats.1.value': '200+',
    'stats.1.label': 'شاحنة تم تجهيزها',
    'stats.1.desc': 'عبر كامل التراب الجزائري',
    'stats.2.value': '100%',
    'stats.2.label': 'مطابقة لمعايير التبريد ATP',
    'stats.2.desc': 'ضمان كامل لسلسلة التبريد',
    'stats.3.value': '24/7',
    'stats.3.label': 'الدعم والخدمات الفنية',
    'stats.3.desc': 'مساعدة وصيانة في قسنطينة',
    // ServicesSection
    'services.badge': 'خبرة معتمدة',
    'services.title': 'حلول الهياكل والتبريد للشاحنات',
    'services.subtitle': 'من الهياكل المتينة والصفائح القوية إلى وحدات التبريد الذكية، نقدم مزيجاً متكاملاً من الهندسة الميكانيكية والحرارية لتجهيز مركباتكم.',
    'services.learn_more': 'معرفة المزيد',
    'services.view_main': 'العرض الرئيسي',
    'services.view_tech': 'العرض التقني',
    'services.carrosserie.principale.title': 'عزل معزز مفرغ من الهواء لنقل في درجات الحرارة المنخفضة (-20° م) للمواد المجمدة.',
    'services.carrosserie.principale.desc': 'يقوم مهندسونا وفنيونا بتجهيز وتركيب هذه الهياكل المعتمدة في ورشتنا الحديثة في قسنطينة، مع التحقق من كل مرحلة وفقاً لمعايير العزل الحراري الصارمة.',
    'services.carrosserie.engineering_title': 'مزايا هندسية متكاملة',
    'services.carrosserie.security_title': 'سلامة حرارية معتمدة',
    'services.char.thickness': 'سمك العزل',
    'services.char.thickness_val': '80 مم إلى 100 مم',
    'services.char.k_coeff': 'معامل التوصيل الحراري K',
    'services.char.k_coeff_val': '0.36 واط/متر مربع كلفن (معتمد)',
    'services.char.temp': 'درجة حرارة التشغيل',
    'services.char.temp_val': '-20° م إلى -25° م',
    'services.char.atp': 'شهادة مطابقة ATP',
    'services.char.atp_val': 'FRC (الفئة C)',
    'services.specifications_title': 'المواصفات التقنية والمزايا',
    'services.duration_label': 'فترة الإنجاز:',
    'services.duration_label_avg': 'متوسط فترة الإنجاز المقدرة:',
    'services.duration.carrosserie': '6-14 يوماً',
    'services.duration.refrigeration': '3-5 أيام',
    'services.duration.maintenance': '1-2 يوم',
    'services.estimate_btn': 'تقدير سعر هذا العمل',
    'services.engineering_sheet': 'ورقة هندسة كاربول الصناعية',
    'services.sheet_title': 'هيكل معزول مقوى (الفئة C)',
    'services.sheet_subtitle': 'ألواح ساندوتش عالية الأداء 100 مم',
    'services.warranty_title': 'الضمان والاعتماد الرسمي',
    'services.warranty_desc': 'شهادة مطابقة رسمية معتمدة من المناجم والجهات الحكومية الجزائرية.',
    'services.key_assets': 'المزايا الأساسية',
    'services.characteristics': 'الخصائص والسمات',
    // Services Data
    'services.carrosserie.title': 'تركيب هياكل الشاحنات',
    'services.carrosserie.description': 'تصميم وتركيب هياكل صناعية متينة: شاحنات مغلقة عازلة، منصات بجوانب، وهياكل قلابة معززة.',
    'services.carrosserie.longDescription': 'نقوم بتصنيع وتجميع هياكل صناعية مخصصة تناسب جميع أنواع شاسيهات الشاحنات (شاحنات صغيرة، شاحنات متوسطة، شاحنات ثقيلة). باستخدام ألواح عازلة عالية الكثافة ومقاطع معدنية مقاومة للصدأ من الدرجة الأولى، نضمن مقاومة الماء والمتانة والقوة الميكانيكية في ظل الظروف الجوية والطرق في الجزائر.',
    'services.carrosserie.adv.0': 'ألواح مركبة معززة عالية الكثافة',
    'services.carrosserie.adv.1': 'أرضية مانعة للانزلاق ومقاومة للماء والاهتراء',
    'services.carrosserie.adv.2': 'حواف زاوية من الألمنيوم المؤكسد أو الفولاذ المقاوم للصدأ',
    'services.carrosserie.adv.3': 'اعتماد مطابق لمعايير السلامة والحمولة الرسمية',
    'services.carrosserie.adv.4': 'ضمان الشركة المصنعة لمدة 24 شهرًا على الهيكل',

    'services.refrigeration.title': 'تركيب وحدات التبريد',
    'services.refrigeration.description': 'دمج مبردات عالية الأداء لنقل المواد سريعة التلف، منتجات الألبان والأدوية (الطازجة والمجمدة).',
    'services.refrigeration.longDescription': 'نحن متخصصون في دمج وصيانة حلول تبريد النقل (وحدات تبريد من ماركات كبرى) مثبتة في المقدمة أو تحت الشاسيه. من الحفاظ على درجات الحرارة الطازجة (+2°م إلى +4°م) إلى التجميد الفائق العميق (-20°م)، تحترم منشآتنا بدقة سلسلة التبريد للخدمات اللوجستية للأغذية والأدوية.',
    'services.refrigeration.adv.0': 'تنظيم دقيق للغاية لدرجة الحرارة عبر معالج دقيق',
    'services.refrigeration.adv.1': 'محركات حرارية أو كهربائية ثنائية الطاقة (طريق/شبكة كهرباء)',
    'services.refrigeration.adv.2': 'عزل حراري ذو معامل توصيل منخفض للغاية للألواح',
    'services.refrigeration.adv.3': 'شهادة مطابقة فنية للسلامة الصحية للتبريد',
    'services.refrigeration.adv.4': 'خدمة الصيانة الوقائية والطارئة على مدار 24 ساعة طوال أيام الأسبوع',

    'services.maintenance.title': 'الصيانة وخدمة ما بعد البيع',
    'services.maintenance.description': 'إصلاح سريع للجسور الحرارية، وإصلاح الهياكل التالفة، وإعادة شحن غاز التبريد.',
    'services.maintenance.longDescription': 'الشاحنة المتوقفة تعني خسارة لشركتك. نحن نوفر ورشة عمل كاملة ومجهزة في قسنطينة لإجراء إعادة شحن غاز التبريد (R404A، R452A)، والكشف عن التسربات، وتقويم الهياكل، واستبدال حشوات الأبواب العازلة، وإصلاح الألواح المركبة.',
    'services.maintenance.adv.0': 'تشخيص فني كامل ومحوسب',
    'services.maintenance.adv.1': 'إعادة شحن بيئية معتمدة وإصلاح الضواغط',
    'services.maintenance.adv.2': 'استبدال سريع للمفصلات وحشوات الأبواب البالية',
    'services.maintenance.adv.3': 'لحام احترافي للفولاذ المقاوم للصدأ والألمنيوم',
    'services.maintenance.adv.4': 'قطع غيار أصلية ومضمونة',

    // Quote Simulator
    'quote.title': 'محاكي التسعير الصناعي',
    'quote.subtitle': 'قم بتهيئة مشروعك ببضع نقرات واحصل على تقدير ميزانية شفاف بالدينار الجزائري (DZD).',
    'quote.step1': '1. تهيئة الشاحنة',
    'quote.step2': '2. معلومات العميل',
    'quote.truck_type': 'فئة وحجم الشاحنة',
    'quote.truck.carrier_small': 'شاحنة صغيرة ومركبة نفعية (<3.5 طن)',
    'quote.truck.carrier_small.desc': 'مثال: هيونداي بورتر، كيا K2500، شاحنات DFAC الصغيرة',
    'quote.truck.truck_medium': 'شاحنة متوسطة (3.5 طن إلى 12 طن)',
    'quote.truck.truck_medium.desc': 'مثال: إيسوزو NPR، شاحنات JMC، رينو الفئة D',
    'quote.truck.semi_heavy_duty': 'شاحنة ثقيلة صلبة (12 طن إلى 19 طن)',
    'quote.truck.semi_heavy_duty.desc': 'مثال: مرسيدس أكتروس صلب، فولفو FE',
    'quote.truck.special_order': 'طلب خاص / مشروع حسب الطلب',
    'quote.truck.special_order.desc': 'مثال: شاحنة سحب وإنقاذ، رافعة ورشة، منصة مخصصة، رافعة سلة...',
    'quote.body_type': 'نوع الهيكل المطلوب',
    'quote.body.insulated_refrigerated': 'هيكل عازل ومبرد (إيسوثيرم)',
    'quote.body.insulated_refrigerated.desc': 'ألواح ساندوتش عازلة ذات كثافة عالية للبرودة',
    'quote.body.standard_box_dry': 'صندوق شحن جاف قياسي (فورغون جاف)',
    'quote.body.standard_box_dry.desc': 'جدران ألمنيوم صلبة للبضائع العامة والطرود',
    'quote.body.meat_hanging': 'هيكل معزول لنقل اللحوم المعلقة (قلادة)',
    'quote.body.meat_hanging.desc': 'سلاسل وقضبان فولاذية أو ألومنيوم معززة ومثبتة في السقف مع خطافات مقاومة للصدأ',
    'quote.body.subframe_only': 'شاسيه فرعي عاري فقط',
    'quote.body.subframe_only.desc': 'إطار معدني مخصص وجاهز لاستقبال معداتك الخاصة',
    'quote.frigo_capacity': 'سعة وقوة التبريد المطلوبة',
    'quote.frigo.none': 'لا يوجد (نقل جاف / عازل بسيط بدون محرك)',
    'quote.frigo.none.desc': 'بدون وحدة إنتاج تبريد نشطة',
    'quote.frigo.positive_fresh': 'تبريد إيجابي طازج (+2° م إلى +4° م)',
    'quote.frigo.positive_fresh.desc': 'مثالي لمنتجات الألبان الطازجة، الخضروات، الفواكه والزهور',
    'quote.frigo.negative_deep_freeze': 'تبريد سلبي مجمد (-18° م إلى -20° م)',
    'quote.frigo.negative_deep_freeze.desc': 'للمثلجات، اللحوم، الأسماك والأطعمة المجمدة والمخزنة',
    'quote.frigo.dual_multi_temp': 'تبريد ثنائي درجة الحرارة (مقصورات متعددة)',
    'quote.frigo.dual_multi_temp.desc': 'حاجز متحرك لنقل المنتجات الطازجة والمجمدة في آن واحد',
    'quote.options': 'خيارات إضافية',
    'quote.option.subframe': 'تضمين شاسيه فرعي من الفولاذ المجلفن (+ معالجة ضد الصدأ والتآكل)',
    'quote.truck_count': 'عدد الشاحنات المطلوب تجهيزها',
    'quote.client.title': 'معلومات الاتصال الخاصة بك لإنهاء التسعير',
    'quote.client.desc': 'سيتصل بك مستشار فني من قسنطينة في غضون 24 ساعة للتحقق من الجدوى الفنية لمشروعك.',
    'quote.client.name': 'الاسم الكامل / اسم جهة الاتصال',
    'quote.client.phone': 'رقم الهاتف المحمول (الجزائر)',
    'quote.client.email': 'البريد الإلكتروني المهني',
    'quote.client.company': 'اسم الشركة (اختياري)',
    'quote.client.city': 'مدينة التشغيل الرئيسية لشاحناتك',
    'quote.client.notes': 'ملاحظات خاصة أو طلبات محددة (مثال: رافعة خلفية، ماركة تبريد مفضلة...)',
    'quote.btn.previous': 'الخطوة السابقة',
    'quote.btn.next': 'متابعة',
    'quote.btn.reset': 'إعادة تعيين المحاكي',
    'quote.result.title': 'تقدير الميزانية الخاص بك',
    'quote.result.subtitle': 'تقدير التكلفة الصناعية على أساس أسعار ورشتنا في قسنطينة',
    'quote.result.bodywork': 'تكلفة الهيكل (الصندوق)',
    'quote.result.frigo': 'تكلفة وحدة التبريد',
    'quote.result.subframe': 'تكلفة الشاسيه الفرعي',
    'quote.result.engineering': 'الهندسة والتركيب والتوصيل بالكبينة',
    'quote.result.ht': 'الإجمالي الفرعي غير شامل الضرائب (HT)',
    'quote.result.tva': 'الضريبة المقدرة (19% ت.ق.م)',
    'quote.result.ttc': 'الإجمالي شامل كل الضرائب (TTC)',
    'quote.result.duration': 'فترة التصنيع المقدرة',
    'quote.result.warranty': 'الضمان المصنعي القياسي',
    'quote.result.note': 'هذا التسعير هو تقدير تقريبي يعتمد على الأسعار الصناعية لورشتنا في قسنطينة. سيتم تقديم العرض النهائي الثابت بعد الفحص الفني الفعلي لشاسيه شاحنتك.',
    'quote.result.pdf': 'تحميل ملف ورقة التسعير PDF',
    'quote.result.contact': 'حجز موعد في ورشة قسنطينة',
    'quote.pdf.alert': 'جاري إعداد وتحميل ورقة تقدير السعر بصيغة PDF...',
    'quote.rdv.alert': 'تم بدء طلب الاتصال مع ورشة كاربول الصناعية بقسنطينة.',

    // GallerySection
    'gallery.title': 'معرض الإنجازات والمشاريع',
    'gallery.subtitle': 'اكتشف آخر المشاريع التي قمنا بتسليمها من ورشنا في قسنطينة.',
    'gallery.cat.all': 'كل المشاريع والخدمات',
    'gallery.cat.carrosserie': 'الهياكل المعزولة',
    'gallery.cat.frigo': 'وحدات التبريد',
    'gallery.cat.realisation': 'شاحنات جاهزة للتسليم',
    'gallery.location_prefix': 'الموقع: ',
    'gallery.real_label': 'معرض الصور الحقيقية',
    'gallery.imm_title': 'جولة حية داخل ورشتنا في قسنطينة',
    'gallery.imm_desc': 'شاهد صوراً حقيقية لمهندسينا أثناء تجميع الألواح العازلة فائقة الدقة وربط دارات التبريد والتحكم.',
    'gallery.cat_body': 'اللحام وتجهيز الهيكل',
    'gallery.cat_cooling': 'تركيب أجهزة التبريد',
    'gallery.cat_deliv': 'تسليم المركبة للعميل',
    'gallery.std_title': 'معايير جودة الإنجاز',
    'gallery.std_item1': 'فحص تسرب الحرارة بالكاميرا الحرارية والأشعة تحت الحمراء',
    'gallery.std_item2': 'اختبار ضغط الغاز وتأكيد العزل والكتامة التامة',
    'gallery.std_item3': 'أقفال ومفصلات مقاومة للاهتزاز والصدمات من الفولاذ المقاوم للصدأ',
    'gallery.std_btn': 'احصل على تقدير سعر لمعدات مماثلة',
    'gallery.item.real-1.title': 'تجميع الهيكل المعزول (إيسوثيرم)',
    'gallery.item.real-1.desc': 'فنيونا أثناء عملية تجميع الألواح المركبة المعزولة عالية الكثافة على شاحنة متوسطة في ورشتنا الجديدة.',
    'gallery.item.real-1.loc': 'الورشة المركزية، قسنطينة',
    'gallery.item.real-2.title': 'تركيب وحدة تبريد كاريير (Carrier)',
    'gallery.item.real-2.desc': 'التركيب النهائي والتوصيل الكهربائي لنظام تبريد سلبي (-18° م) على الجدار الأمامي لشاحنة توزيع المواد المجمدة.',
    'gallery.item.real-2.loc': 'المنطقة الصناعية، قسنطينة',
    'gallery.item.real-3.title': 'شاحنة تبريد جاهزة للتسليم النهائي',
    'gallery.item.real-3.desc': 'مشروع تكامل وتجهيز كامل (صندوق معزول ومقاوم للماء بالكامل + وحدة تبريد ومراقبة حرارية) تم تسليمه لشركة نقل الحليب ومشتقاته.',
    'gallery.item.real-3.loc': 'الهضاب العليا، قسنطينة',
    'gallery.item.real-4.title': 'التجهيز الداخلي الدقيق لصندوق التبريد',
    'gallery.item.real-4.desc': 'أرضية مضلعة من الألمنيوم المقاوم للماء بالكامل، سكك تثبيت الشحنات وستائر حرارية شريطية لتقليل فقدان التبريد أثناء التفريغ.',
    'gallery.item.real-4.loc': 'ورشة اللمسات الأخيرة، قسنطينة',
    'gallery.item.real-5.title': 'أسطول شاحنات توزيع منتجات الألبان',
    'gallery.item.real-5.desc': 'تسليم متزامن لثلاث شاحنات تبريد كبيرة مجهزة بحواجز متحركة متعددة درجات الحرارة للتوزيع الحضري السريع.',
    'gallery.item.real-5.loc': 'قسنطينة، الجزائر',

    // AboutSection
    'about.badge': 'من نحن؟',
    'about.title1': 'كاربول الصناعية:',
    'about.title2': 'الرائد في تبريد وهياكل الشاحنات',
    'about.p1': 'تأسست شركة كاربول الصناعية في قسنطينة، القلب اللوجستي للشرق الجزائري، بهدف تزويد شركات النقل والصناعات الغذائية بمعدات عزل وتبريد ذات موثوقية تامة.',
    'about.p2': 'نحن نجمع بين تقنيات العزل الحديثة للألواح المركبة (ألواح ساندوتش خفيفة الوزن ومقاومة للماء بالكامل) مع مهارات غلاية الصفائح الثقيلة لضمان منشآت قوية ومستدامة. سواء كانت شاحنة توزيع صغيرة في وسط المدينة أو مقطورة ثقيلة مفصلية، فإننا نقوم بتخصيص طاقات التبريد لتتحمل درجات الحرارة القصوى للمناخ الجزائري.',
    'about.val.0.title': 'انعدام الجسور الحرارية',
    'about.val.0.desc': 'طريقتنا الحصرية في القولبة الحرارية للحواجز تعزل الشحنة تمامًا عن العوامل الخارجية.',
    'about.val.1.title': 'لحام وخراطة احترافية',
    'about.val.1.desc': 'يتم لحام وتثبيت الشاسيه الفرعي باستخدام فولاذ مقسى معالج بالكامل ضد الصدأ والتآكل.',
    'about.val.2.title': 'اعتماد ومطابقة رسمية',
    'about.val.2.desc': 'تحصل جميع مركباتنا المعدلة على شهادة مطابقة واستلام رسمية صادرة عن المناجم.',
    'about.val.3.title': 'مرافقة وصيانة محلية',
    'about.val.3.desc': 'ورشة صيانة قريبة متواجدة في قسنطينة لضمان الخدمة السريعة لأسطول شاحناتك.',
    'about.sede': 'المقر الرئيسي والورشة المركزية',
    'about.address': 'الشعب الرصاص، حصة F رقم M1، قسنطينة، الجزائر',
    'about.extra_title': 'هل تملك بالفعل وحدة التبريد الخاصة بك؟',
    'about.extra_desc': 'نحن نضمن التركيب الميكانيكي والتوصيل الكهربائي لوحدات التبريد الخاصة بك (جديدة أو مستعملة مجددة) بأسعار تنافسية للغاية، مع توصيل آمن بكابينة السائق.',
    'about.extra_btn': 'تحدث إلى فني تركيب',

    // Testimonials
    'testimonials.title': 'ماذا يقول عملاؤنا؟',
    'testimonials.role1': 'مدير العمليات اللوجستية',
    'testimonials.company1': 'ملبنة قسنطينة',
    'testimonials.comment1': 'لقد عهدنا بتجهيز 12 شاحنة لجمع وتوزيع الحليب إلى كاربول الصناعية. جودة العزل الحراري ممتازة حتى تحت حرارة الصيف الشديدة في الشرق الجزائري. درجات الحرارة تبقى ثابتة ومستقرة واستهلاك الوقود لوحدات التبريد لدينا أصبح مثاليًا وموفرًا.',
    'testimonials.role2': 'ناقل مستقل',
    'testimonials.company2': 'ش.ذ.م.م زواوي وأولاده لنقل المبرد',
    'testimonials.comment2': 'خدمة ما بعد البيع مذهلة وسريعة! بعد تعرض شاحنتي لحادث طفيف على طريق باتنة، قام فريق كاربول بإصلاح جدار الهيكل العازل وتغيير مكثف المبرد في أقل من 48 ساعة. سرعة واحترافية لا مثيل لها في قسنطينة.',
    'testimonials.role3': 'مديرة المشتريات والتموين',
    'testimonials.company3': 'فارم إيست الجزائر للأدوية',
    'testimonials.comment3': 'لتوزيع المنتجات الصيدلانية والأدوية الحساسة، فإن شهادة المطابقة والمعايرة الدقيقة لدرجة الحرارة أمر لا غنى عنه. ساعدنا محاكي الأسعار على تخطيط ميزانيتنا الاستثمارية بدقة، وقام فريقهم الفني بدمج غرفتين ثنائيتي درجة الحرارة بنجاح تام.',

    // ContactSection
    'contact.title': 'لديك سؤال؟ أو مشروع ترغب في تجسيده؟',
    'contact.subtitle': 'فريق المبيعات والمهندسين لدينا مستعدون دائمًا للاستماع إليكم وتصميم مركباتكم المثالية.',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.tel': 'الهاتف وواتساب',
    'contact.info.email': 'البريد الإلكتروني للاتصال',
    'contact.info.addr': 'عنوان الورشة',
    'contact.info.addr_desc': 'الشعب الرصاص، حصة F رقم M1، قسنطينة',
    'contact.info.hours': 'ساعات العمل الرسمية',
    'contact.info.hours_desc': 'السبت - الخميس: 08:00 صباحًا - 17:00 مساءً (الجمعة عطلة أسبوعية)',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.company': 'اسم الشركة',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.subject': 'موضوع الرسالة',
    'contact.form.message': 'نص رسالتك',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.placeholder.name': 'مثال: أحمد بن علي',
    'contact.form.placeholder.company': 'مثال: شركة ترانس لوجستيك للخدمات',
    'contact.form.placeholder.email': 'مثال: contact@entreprise.dz',
    'contact.form.placeholder.subject': 'مثال: طلب تسعيرة صندوق معزول لشاحنة إيسوزو',
    'contact.form.placeholder.message': 'يرجى وصف مشروعك، نوع وطراز شاسيه الشاحنة، ودرجة الحرارة المطلوبة للنقل...',
    'contact.form.success': 'تم إرسال رسالتك بنجاح! سيقوم فريقنا التجاري بالرد عليكم في أقرب وقت ممكن.',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.0.q': 'ما هي شهادة المطابقة الحرارية الرسمية ATP في الجزائر؟',
    'contact.faq.0.a': 'شهادة المطابقة العازلة هي مستند تنظيمي إلزامي يصدر بعد التركيب الفني من قبل خدمتنا المعتمدة. تشهد بأن جدار الصندوق ووحدة التبريد يحافظان تماماً على درجة الحرارة المطلوبة (-20° م أو +4° م) لضمان السلامة الصحية العامة تحت ظروف المناخ الحار جداً في الجزائر.',
    'contact.faq.1.q': 'ما هي العلامات التجارية لوحدات التبريد التي تقومون بتركيبها؟',
    'contact.faq.1.a': 'نقوم بتركيب وتوصيل مبردات عالمية رائدة مثل Carrier، Thermo King، Zanotti، و Dongin Thermo. ورشتنا مجهزة بجميع التوصيلات والضفائر الكهربائية الأصلية وأنظمة البرمجة الرقمية المخصصة لهذه العلامات التجارية.',
    'contact.faq.2.q': 'هل تقدمون خدمة صيانة الهياكل فقط بدون وحدة التبريد؟',
    'contact.faq.2.a': 'نعم، بكل تأكيد. بالإضافة إلى التجهيز والتركيب الأولي، تقوم ورشتنا بصيانة وإصلاح الجسور الحرارية التالفة، لحام الفولاذ المقاوم للصدأ للأرضيات، استبدال الستائر الشريطية العازلة، ومعالجة تسريبات الأبواب الخلفية.',
    'contact.faq.3.q': 'ما هي فترات تجهيز الشاحنات في ورشتكم بقسنطينة؟',
    'contact.faq.3.a': 'بالنسبة للتركيب البسيط لوحدة تبريد جاهزة، تستغرق العملية من 2 إلى 4 أيام عمل. أما بالنسبة للتصنيع المتكامل للصندوق العازل المصنوع بالكامل على المقاس (الألواح + الشاسيه الفرعي + المبرد)، تستغرق العملية من 6 إلى 14 يوماً وفقاً لحجم شاسيه الشاحنة.',

    // Quote Simulator Extra
    'quote.free_estimate_badge': 'طلب تقدير سعر مجاني',
    'quote.step1_title': '1. نوع الشاسيه / المركبة',
    'quote.step2_title': '2. نوع الهيكل / الصندوق',
    'quote.step3_title': '3. قدرة وحدة التبريد / حرارة التشغيل',
    'quote.step4_title': '4. عدد الشاحنات المطلوب تجهيزها',
    'quote.subframe_option': 'شاسيه فرعي مجلفن',
    'quote.subframe_desc': 'معالجة مضادة للتآكل',
    'quote.notes_placeholder': 'مثال: طلب رافعة خلفية، حاجز متحرك عازل، أبواب جانبية مزدوجة، رفوف قابلة للطي...',
    'quote.result.title_badge': 'بطاقة المواصفات الفنية للطلب',
    'quote.result.recap_title': 'ملخص المواصفات المهيأة',
    'quote.result.carrier': '1. الشاسيه والمركبة',
    'quote.result.structure': '2. نوع الهيكل',
    'quote.result.cooling': '3. وحدة التبريد والتكييف',
    'quote.result.quantity': '4. كمية الشاحنات',
    'quote.result.additional': 'الخيارات الإضافية',
    'quote.result.subframe_galva': 'شاسيه فرعي مجلفن معالج بالكامل ضد الصدأ',
    'quote.result.delay_label': 'فترة العمل المتوقعة بالورشة:',
    'quote.result.warranty_label': 'الضمان المصنعي لكاربول:',
    'services.mois': 'أشهر',
    'quote.result.delivery_place': 'مكان التسليم النهائي:',
    'quote.result.delivery_val': 'ورشة قسنطينة',
    'quote.client.name_placeholder': 'مثال: كريم بن حاج',
    'quote.client.phone_placeholder': 'مثال: XX XX XX 0550',
    'quote.client.company_placeholder': 'مثال: شركة ترانس لوجستيكس فريد',
    'quote.result.notice': 'لضمان أعلى جودة وأفضل الأسعار في الجزائر، يتم دراسة وتصميم كل طلب على حدة من قبل مهندسينا الفنيين لتلبية احتياجاتك الفعلية بدقة.',
    'quote.success.title': 'تم إرسال طلب التسعيرة بنجاح!',
    'quote.success.thank_you': 'شكراً {name}. تم تسجيل طلبك بنجاح برقم مرجعي فريد: {ref}.',
    'quote.success.recap': 'الملخص المستلم للمشروع',
    'quote.success.flotte': 'الأسطول المهيأ:',
    'quote.success.structure': 'نوع الهيكل المختار:',
    'quote.success.cooling_sys': 'نظام التبريد المستعمل:',
    'quote.success.subframe': 'الشاسيه الفرعي:',
    'quote.success.subframe_val': 'الشاسيه الفرعي المجلفن متضمن',
    'quote.success.notice': 'يقوم مهندسو مكتب الدراسات لورشة قسنطينة بإعداد عروض الأسعار والجدوى، وسيتصلون بك على الرقم {phone} خلال 60 دقيقة لتأكيد المواصفات والمخططات الهندسية لشاحناتك.',
    'quote.success.btn_another': 'إجراء طلب تسعيرة آخر',
    'quote.error_fill': 'يرجى إدخال اسمك الكامل ورقم هاتفك الجوال بشكل صحيح.',
    'quote.body_warning': '* يتطلب تركيب وحدة تبريد نشطة اختيار هيكل من نوع "هيكل عازل ومبرد (إيسوثيرم)".',
    'quote.days_work': 'أيام عمل',

    // Footer
    'footer.desc': 'الرائد في صناعة الهياكل والتبريد الصناعي للشاحنات في الشرق الجزائري.',
    'footer.links': 'روابط سريعة',
    'footer.rights': 'جميع الحقوق محفوظة.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('carp_lang');
    return (saved === 'ar' || saved === 'fr') ? saved : 'fr';
  });

  useEffect(() => {
    localStorage.setItem('carp_lang', lang);
    const htmlEl = document.documentElement;
    if (lang === 'ar') {
      htmlEl.setAttribute('dir', 'rtl');
      htmlEl.setAttribute('lang', 'ar');
    } else {
      htmlEl.setAttribute('dir', 'ltr');
      htmlEl.setAttribute('lang', 'fr');
    }
  }, [lang]);

  const t = (key: string): string => {
    const translationSet = translations[lang] || translations['fr'];
    return translationSet[key] || translations['fr'][key] || key;
  };

  const isRtl = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
